# Generated by Django 5.2.5 on 2025-08-21 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('muscles_group', models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('arms', 'Arms'), ('core', 'Core'), ('legs', 'Legs')], max_length=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('weight_goal', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', "I don't want to share")], default='N', max_length=1)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary'), ('light', 'Lightly active'), ('moderate', 'Moderately active'), ('very', 'Very active'), ('extra', 'Extra active')], default='sedentary', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type_of_program', models.CharField(choices=[('Upper body', 'Workout for upper body'), ('Legs day', 'Workout for legs'), ('Core', 'Workout for core muscles'), ('Yoga', 'Yoga workout'), ('Pilates', 'Pilates'), ('Stretching', 'Stretching')], max_length=25)),
                ('time', models.DurationField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_workouts', to=settings.AUTH_USER_MODEL)),
                ('exercises', models.ManyToManyField(related_name='+', to='sports_app.exercise')),
                ('saved_by', models.ManyToManyField(related_name='saved_workouts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
