# Generated by Django 5.2.5 on 2025-08-21 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0002_alter_workout_exercises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_workouts', to='sports_app.profile'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='saved_by',
            field=models.ManyToManyField(related_name='saved_workouts', to='sports_app.profile'),
        ),
    ]
