# Generated by Django 5.2.5 on 2025-08-21 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0003_alter_workout_author_alter_workout_saved_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DurationField(blank=True, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='sports_app.profile')),
                ('workout', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routine_workout', to='sports_app.workout')),
            ],
        ),
    ]
