# Generated by Django 5.2.5 on 2025-08-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0004_workoutroutine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutroutine',
            old_name='datetime',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='workoutroutine',
            name='profile',
        ),
        migrations.AddField(
            model_name='workoutroutine',
            name='profile',
            field=models.ManyToManyField(related_name='routines', to='sports_app.profile'),
        ),
    ]
