# Generated by Django 5.2.5 on 2025-08-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0005_rename_datetime_workoutroutine_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='name',
            field=models.CharField(default='Exercise', max_length=100),
        ),
    ]
