# Generated by Django 5.2.5 on 2025-08-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0006_exercise_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
