# Generated by Django 5.2.5 on 2025-08-24 11:08

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0009_alter_exercise_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='muscles_group',
            field=models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('arms', 'Arms'), ('core', 'Core'), ('legs', 'Legs'), ('cardio', 'Cardio')], max_length=10),
        ),
    ]
