# Generated by Django 5.2.5 on 2025-08-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0010_alter_exercise_image_alter_exercise_muscles_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.IntegerField(default=3)),
                ('reps', models.IntegerField(default=8)),
                ('rest', models.DurationField(blank=True, null=True)),
            ],
        ),
    ]
