# Generated by Django 5.2.5 on 2025-08-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0012_remove_workout_exercises_remove_workout_saved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
