# Generated by Django 5.2.5 on 2025-08-25 12:02

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0013_alter_workout_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='type_of_program',
            field=models.CharField(choices=[('Upper body', 'Workout for upper body'), ('Legs day', 'Workout for legs'), ('Core', 'Workout for core muscles'), ('Yoga', 'Yoga workout'), ('Pilates', 'Pilates'), ('Stretching', 'Stretching'), ('Cardio', 'Cardio workout')], max_length=25),
        ),
        migrations.AlterField(
            model_name='workoutroutine',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='workoutroutine',
            name='workout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routine_workout', to='sports_app.workout'),
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], max_length=10)),
                ('repeat_weekly', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to='sports_app.profile')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plan', to='sports_app.workout')),
            ],
        ),
    ]
