# Generated by Django 5.2.5 on 2025-08-25 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0014_workout_image_alter_workout_type_of_program_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutplan',
            name='weekday',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='workout',
        ),
        migrations.CreateModel(
            name='WorkoutSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], max_length=10)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='sports_app.workout')),
                ('workout_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='sports_app.workoutplan')),
            ],
        ),
    ]
