# Generated by Django 5.2.5 on 2025-08-25 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0015_remove_workoutplan_weekday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutexercise',
            name='workout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercises', to='sports_app.workout'),
        ),
    ]
