# Generated by Django 5.2.5 on 2025-08-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0016_alter_workoutexercise_workout'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='date_finish',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='name',
            field=models.CharField(default='aboba', max_length=100),
            preserve_default=False,
        ),
    ]
