# Generated by Django 5.2.5 on 2025-08-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0017_workoutplan_date_finish_workoutplan_date_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='description',
            field=models.TextField(default='author did not provide any description but maybe this workout name says everything...'),
        ),
    ]
