# Generated by Django 5.2.5 on 2025-08-26 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0018_workout_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutplan',
            name='date_finish',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='date_start',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='repeat_weekly',
        ),
    ]
