# Generated by Django 5.2.5 on 2025-08-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0019_remove_workoutplan_date_finish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='current',
            field=models.BooleanField(default=False),
        ),
    ]
