# Generated by Django 5.2.5 on 2025-08-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0020_workoutplan_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='days_per_week',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
